package com.buaa.backkom.miaosha.dao;

import com.buaa.backkom.miaosha.dataobject.SeqDO;
import org.springframework.stereotype.Component;

@Component
public interface SeqDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    int insert(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    int insertSelective(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    SeqDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    int updateByPrimaryKeySelective(SeqDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbggenerated Sat Sep 19 19:43:03 CST 2020
     */
    int updateByPrimaryKey(SeqDO record);
    
    SeqDO selectByName (String name);
}