package com.buaa.backkom.miaosha.dao;

import com.buaa.backkom.miaosha.dataobject.UserDO;
import org.apache.catalina.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Component
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Sep 18 11:22:38 CST 2020
     */
    int insert(UserDO record);

    /**
     * 这种方法的好处在于，对于传入的参数为null的时候，它能够不insert该字段，而是由数据库决定字段值
     * @mbggenerated Fri Sep 18 11:22:38 CST 2020
     */
    int insertSelective(UserDO record);
    
    /**
     *
     * @param id
     * @return
     */
    UserDO selectById(Integer id);
    
    UserDO selectBytelephone(String telephone);
}